name: Build Debian package

on:
  push:
  pull_request:

jobs:
  build-deb:
    runs-on: ubuntu-24.04-arm
    container:
      image: debian:13.1
    env:
      DEBIAN_FRONTEND: 'noninteractive'
    steps:
      - name: Install build dependencies
        run: |
          apt update
          apt install -y \
            build-essential \
            debhelper \
            devscripts \
            dh-python \
            git \
            python3-all \
            python3-build \
            python3-hatchling \
            pybuild-plugin-pyproject \
            python3-pytest \
            python3-pytest-cov

      - name: Setup non-root user
        run: |
          useradd -m builder
          mkdir -p /home/builder/.cache
          chown -R builder:builder /home/builder
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show versions (debug)
        run: |
          python3 --version
          debuild --version

      - name: Build package
        run: |
          su builder -c "
          cd $GITHUB_WORKSPACE
          debuild -us -uc -b
          mkdir $GITHUB_WORKSPACE/artifacts
          cp ../*.deb ../*.changes ../*.buildinfo $GITHUB_WORKSPACE/artifacts/
          "

      - name: Run lintian
        run: |
          lintian $GITHUB_WORKSPACE/artifacts/*.changes || true

      - name: Upload .deb artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: |
            $GITHUB_WORKSPACE/artifacts/*.deb
            $GITHUB_WORKSPACE/artifacts/*.changes
            $GITHUB_WORKSPACE/artifacts/*.buildinfo
